spring.application.name=repo-service
server.port=8082


# ==========================================
# PostgreSQL - Aiven
# ==========================================

spring.datasource.url=jdbc:postgresql://pg-1e60fa7f-devanshrawat2005-46c2.c.aivencloud.com:27624/anchor_users?sslmode=require

spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# Actuator
# ==========================================

management.endpoints.web.exposure.include=health,info

# ==========================================
# Kafka
# ==========================================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.properties.spring.json.add.type.headers=false

# GitHub
github.api.base-url=https://api.github.com
github.token=${GITHUB_TOKEN}