# ==========================================
# Application
# ==========================================

spring.application.name=user-service
server.port=8081


# ==========================================
# PostgreSQL
# ==========================================

spring.datasource.url=jdbc:postgresql://pg-1e60fa7f-devanshrawat2005-46c2.c.aivencloud.com:27624/anchor_users?sslmode=require

spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ==========================================
# JWT
# ==========================================

jwt.secret=change-this-to-a-long-random-secret-key-for-development-only

jwt.expiration=3600000


# ==========================================
# Actuator
# ==========================================

management.endpoints.web.exposure.include=health,info